### ISSUE TITLE
Error with custom voice

### ISSUE THREAD

**Issue by anzestrela** [matatonic/openedai-speech#15]
Hi, I have added ```voices/glados.onnx``` and ```voices/glados.onnx.json``` from: https://github.com/dnhkng/GlaDOS
I have also added ```  glados:
    model: voices/glados.onnx
    speaker: 163``` to ```config/voice_to_speaker.yaml``` and  ```config/voice_to_speaker.default.yaml```

The voice is not generated and the server prints: ```
INFO:     192.168.64.113:37818 - "POST /v1/audio/speech HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/root/audio/openedai-speech/.venv/bin/piper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/audio/openedai-speech/.venv/lib/python3.11/site-packages/piper/__main__.py", line 126, in main
    for audio_bytes in audio_stream:
  File "/root/audio/openedai-speech/.venv/lib/python3.11/site-packages/piper/voice.py", line 123, in synthesize_stream_raw
    yield self.synthesize_ids_to_raw(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/audio/openedai-speech/.venv/lib/python3.11/site-packages/piper/voice.py", line 166, in synthesize_ids_to_raw
    audio = self.session.run(
            ^^^^^^^^^^^^^^^^^
  File "/root/audio/openedai-speech/.venv/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid input name: sid```

OS: debian 12
python: 3.11
curl: ```
curl http://192.168.73.78:8000/v1/audio/speech -H "Content-Type: application/json" -d '{
    "model": "tts-1",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "glados",
    "response_format": "mp3",
    "speed": 1.0
  }' > speech.mp3```

Thank you.

**Comment by matatonic** [comment]
No issue? I didn't get around to test custom onnx yet, is it working?
