### ISSUE TITLE
OSError: [Errno 101] Network is unreachable on Macbook 

### ISSUE THREAD

**Issue by sanpatricky** [matatonic/openedai-speech#75]
The latest error is in below

**Comment by sanpatricky** [comment]
I deleted the container and the image I built in the above error, then I use docker-compose to start container with command 'docker compose -f docker-compose.min.yml up -d', new error occurred:

2024-10-28 18:57:52 server-1  | Traceback (most recent call last):
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
2024-10-28 18:57:52 server-1  |     h.request(req.get_method(), req.selector, req.data, headers,
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/http/client.py", line 1303, in request
2024-10-28 18:57:52 server-1  |     self._send_request(method, url, body, headers, encode_chunked)
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/http/client.py", line 1349, in _send_request
2024-10-28 18:57:52 server-1  |     self.endheaders(body, encode_chunked=encode_chunked)
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/http/client.py", line 1298, in endheaders
2024-10-28 18:57:52 server-1  |     self._send_output(message_body, encode_chunked=encode_chunked)
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/http/client.py", line 1058, in _send_output
2024-10-28 18:57:52 server-1  |     self.send(msg)
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/http/client.py", line 996, in send
2024-10-28 18:57:52 server-1  |     self.connect()
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/http/client.py", line 1468, in connect
2024-10-28 18:57:52 server-1  |     super().connect()
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/http/client.py", line 962, in connect
2024-10-28 18:57:52 server-1  |     self.sock = self._create_connection(
2024-10-28 18:57:52 server-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
2024-10-28 18:57:52 server-1  |     raise exceptions[0]
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
2024-10-28 18:57:52 server-1  |     sock.connect(sa)
**2024-10-28 18:57:52 server-1  | OSError: [Errno 101] Network is unreachable**
2024-10-28 18:57:52 server-1  | 
2024-10-28 18:57:52 server-1  | During handling of the above exception, another exception occurred:
2024-10-28 18:57:52 server-1  | 
2024-10-28 18:57:52 server-1  | Traceback (most recent call last):
2024-10-28 18:57:52 server-1  |   File "/usr/local/bin/piper", line 8, in <module>
2024-10-28 18:57:52 server-1  |     sys.exit(main())
2024-10-28 18:57:52 server-1  |              ^^^^^^
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/site-packages/piper/__main__.py", line 104, in main
2024-10-28 18:57:52 server-1  |     ensure_voice_exists(args.model, args.data_dir, args.download_dir, voices_info)
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/site-packages/piper/download.py", line 122, in ensure_voice_exists
2024-10-28 18:57:52 server-1  |     with urlopen(file_url) as response, open(
2024-10-28 18:57:52 server-1  |          ^^^^^^^^^^^^^^^^^
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
2024-10-28 18:57:52 server-1  |     return opener.open(url, data, timeout)
2024-10-28 18:57:52 server-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
2024-10-28 18:57:52 server-1  |     response = self._open(req, data)
2024-10-28 18:57:52 server-1  |                ^^^^^^^^^^^^^^^^^^^^^
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
2024-10-28 18:57:52 server-1  |     result = self._call_chain(self.handle_open, protocol, protocol +
2024-10-28 18:57:52 server-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
2024-10-28 18:57:52 server-1  |     result = func(*args)
2024-10-28 18:57:52 server-1  |              ^^^^^^^^^^^
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
2024-10-28 18:57:52 server-1  |     return self.do_open(http.client.HTTPSConnection, req,
2024-10-28 18:57:52 server-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
2024-10-28 18:57:52 server-1  |     raise URLError(err)
2024-10-28 18:57:52 server-1  | urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
2024-10-28 18:57:52 server-1  | Traceback (most recent call last):
2024-10-28 18:57:52 server-1  |   File "/usr/local/bin/piper", line 8, in <module>
2024-10-28 18:57:52 server-1  |     sys.exit(main())
2024-10-28 18:57:52 server-1  |              ^^^^^^
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/site-packages/piper/__main__.py", line 104, in main
2024-10-28 18:57:52 server-1  |     ensure_voice_exists(args.model, args.data_dir, args.download_dir, voices_info)
2024-10-28 18:57:52 server-1  |   File "/usr/local/lib/python3.11/site-packages/piper/download.py", line 56, in ensure_voice_exists
2024-10-28 18:57:52 server-1  |     raise VoiceNotFoundError(name)
2024-10-28 18:57:52 server-1  | piper.download.VoiceNotFoundError: en_US-libritts_r-medium
2024-10-28 18:57:53 server-1  | INFO:     Started server process [20]
2024-10-28 18:57:53 server-1  | INFO:     Waiting for application startup.
2024-10-28 18:57:53 server-1  | INFO:     Application startup complete.
2024-10-28 18:57:53 server-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**Comment by sanpatricky** [comment]
Is it caused by lack of onnx? I have not installed any onnx file and config. But log show the error is network related.

**Comment by matatonic** [comment]
This error is from downloading piper voices, not onnx. This seems to be related to your network setup, can you access huggingface.co and github.com from the computer?

**Comment by sanpatricky** [comment]
For interesting, may I ask the purpose of openedai-speech connecting to github and huggingface when setup/startup?

**Comment by matatonic** [comment]
Take a look at the startup.min.sh script, it calls the download script for the piper voices so that the default configured voices will work. This is not a hard requirement for the server to start, and if you download the piper model you want in advance, you can ignore the errors from this download failing or comment out the download lines from the startup script and rebuild the docker image (docker compose -f docker-compose.min.yml build). If you do this, be sure that you only use voices that are already configured and downloaded, because piper will download missing voices automatically if you try and use them.
